# Generated by Django 4.0.6 on 2022-07-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JB_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('skill', models.CharField(max_length=100)),
                ('exp', models.IntegerField()),
                ('pay', models.IntegerField()),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
            ],
        ),
    ]
